#!/bin/sh

#
# Name: localsidekiq
# Author: johnny
# Usage: localsidekiq [start|stop|restart|rolling_restart|respawn|quiet]
#
# This command wraps capistrano-sidekiq gem. All commands available
# depend on the gem.
#

cd /home/deploy/ranking_server
LOCAL_DEPLOY=true DEPLOY_REF=dummy bundle exec cap production sidekiq:$1
